services:
- docker
arch:
- arm64
script:
- docker build -t jchorl/librespot .
deploy:
- provider: script
  script: bash deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD
  on:
    branch: master
env:
  global:
  - secure: TmSBtNJCeQQj//vIpnEqXGa+vH4+uYl9lhzMYYm7q79k/S7BCV8DAf03oncNb/3+aJrzbmvwBJ5jrnszspGjkE5W9DnDUzoNQ9/Q/g81VHh9DvD+Jxn4RW+yls5Uy2nSPSNq16HTp7UP37TzM1cnDB0P/KKxepxqjZ17OQ4fsJ9HvzH220RtH4bTavSfbbop153vZlQGDwGQzca+aGz7L9G8LRdX1W+qvWf3MV8v6pgS2X+/R+KxRi7ntng+01t/gPHWuFLJDGEGq+0uBvcbIFB1/cWl4QRp2KmpFzzdvuyim5nmEpxeBj9BT9BbmCp/kHT/ZyBlhld1wJhPqM51ejgJ87qcA1A6sihpKQDEnF33CiLH681/RRTHmgnDfFAbzfX2o3NTFpcYNKiBgbebLvEp5tyDQtglKJrr5VaBV5Zu/FlPAF/lTEOxAU6PFvq5XL03rvfMxLX5EiioNgqAX7HERe/MSUkNYpJVtLR7bmqLX4SemiGAarPvzRT1IC7qYCt5jDecMWucA2BltivIGubF0ThjUOFgFuEdaYSm+zxSy+sAALnrCqEpj1eJgu/QNO/9Xl18UohBHlZyyVZbax+weNRYBDiDdkQA+KKexZ6BU9D/g0iH71q4OfXI1JIRS+/jieDPEvW1a8xLM0mXc/BRMKk/Zod7v0faLkP8PZ4=
  - secure: npUlSmmpPiwKjJ/A5mdX0G8j0Fct9cNUdiwKIJAuuxitu69HqjWr6pN9IpxFUI5yoSdVWkB1So230tHLzZJxrHdpHjnciVRN/Kz5yvIlBS0wguLRP9olJzQ31+0yMD/6PLMXJw/VQtoV20G86AaeyJo6z0jdKsPW7YsdAu/0kCpBzRtR21aSmNFUR3ypn/3dWuK1O9uSrHVnBuFXBu36wHFbwR2bm3yGMprTx9TmXnLnCkC02gWgHj1M+QHOIeNjKLjQc5eJc22YHBcfU+wycCVTzp/UCf4JgZJPPA5UnACzCD6wqciF2ZN/Oaj+wNIUtbH81WTnAcPqw6lS/bX9pP9yqLoQsoo7VtdYZiO6vnxWqNtiECfFhj7v2R+qqlwDxSeMJaQenmkeHlbgnfHGuZEH9dAvkapSGubH1Hdtce0dY9gkjvCuTlbuZxqOwUCULJX3J9qAJrUyR0oRAtNMmHbJ3YyA7RtZ5WZfMbVADEiFFfWjQ8UGAVGvoDN8B86aSEphPLZ4mSB06evvaHcP2Cun4hcwcBLOA+s+tr8N5b9zlLW58WPtgUPPM/gvJzEPU9iM+nwdZPxqBN02xBrAh4p0hN0x84iaohcRdtKve7vuAdQECFLpq0LPAgRdfVKMCN8Nw9KKRHSqAhTZ/JfjC45oALE+35kBeHvyMoEJC0k=
