services:
- docker
arch:
- arm64
script:
- docker build -t jchorl/librespot .
deploy:
- provider: script
  script: bash deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD
  on:
    branch: master
DOCKER_USERNAME:
  secure: O4OBev0Th1c5ZygnTmyZur24plWrF1SER/Z/FBzRsojAx9KpWwNharOyh8Ryn1m38xyp4OPjrQoBZalW00ezlJNuHE+pshdFY/j8j98FQlVDRM52+2f01rN/iQR3+tidhmmVEZRX+30VYm0V6/onweHHhJW90xdXb6zfjg6U1XI+FUZnCLhRPi2uCSgt/a9SDwtXBDytRrlPQyYcuautJtZM4rX2SWTGggxAWayX7LtWsv8UqolatJhCFlw87ihfxVoKLQV5voJqEY12yWMdwMXTBZXoYL9ZS9jAl83sNPTByX2Exo6ZU63TfhdLb4RuJisJbhQ/xQd0BjmBqN4awO6vN93/804B06M+TbSTd911dEVcDrf0nZBXvHuzDu9Vb6L/DDr8ii3nno/kfAK4VHkFgs8v3Lc1PgKQ6p2B/J2BkXv1RrnBcPQtNnwSxV4i9SSMsGqQPqscVayj1yJcs6liwC1mfZbWqoFTxwhuWCk0Lp9AIm7iXmr7NjKLjw60s2KjqU6O2Chd0DRTZNi12NkV2VZwuCh7ksjCnBtM3YKomlUsHVSzwM7Vj9kAlm2USlHOhSsuCaZwNa4xJGFz7LUwER6Npdovb+qkNHD51eWkAQJLf7WaYCXDFfnYOKEYaHU/eG+fyC1FwJrW9dcobnZoxJ2Yxdj2g1GulcHRWls=
DOCKER_PASSWORD:
  secure: AuplT0MNZ18NCgtnn5n/Ha8gj9PFH6aELUyzWZV4IuP9pILiAepKXhmW7yfDkCCP6v00tW0/H11ptxNVIVGglKy0kOMoANCgwHQh2JHYBpUJh2s44bbI+e2H/u9SW2qMAZihuGgntAZmUZEcguA28Ffs/GVfhrn05Fz+ST667GBClmEZVvTJwDz5VfWLWZInZ0I9pPjGcGip/uZETmE5QIix8fe6PW5wAMCeXaQSF6WGNrxtU/R7CmWvatXWtJSDkYTuve9v8aHzHJrz5wAE3V5yZqUbw28P2O3zGaV3XeymqOe9z7P2NYStA0jr1XDyS58RwMx6ReuFPRYYTR18kGW6EHZ77+Q2Y7Pu7lu9GL6VrnEZ1Y0QysYtQaWj1L7dzNGqkLeKgRUBaRVvQGAAu5wEnY9brFSPFYSZ8cbtUZMM3uIg2nc4OJriGvXZWkx7s0LH0LoaRP7KSqQ67spyRavALqF+I3swykpdeucuZmxkkTKHSQ5TbdRWfPR8lAxcHkeOOBu0rPm5PSYMU5ZxQiVvL8LZl+zivAw0OAskOTKovwkv8GA4w41rnHzv4SZiEjYJ1yIOARXc7v0a59aMhRb8QgSvO0CR+3pUvPl+RPpJTTARPHgNCjCrvFbRQBJ2c1AFOjOw3F8Ag8yj62x4JNBeXxIJVoxNwVwkWq1UXr0=
