services:
- docker
arch:
- arm64
script:
- docker build -t jchorl/librespot .
deploy:
- provider: script
  script: bash deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD
  on:
    branch: master
env:
  global:
  - secure: IWQrVgBvE4UKG5EboLDJ5FIbJ8hR2IiHJFjH/wLm3CxdNUW6j0GAZO18GsHVxsegiM3uFDkqfMYQM+xXFIIws+eyYYkjiVqGw4WE+KZqBzDplxLxNyJIIhwFuX+/mC0AnYfMA7MQNy18lfvX1ZlpM8oRvyWY0dviBb5X4m0MJ0ST7qrvS4pC5Gag79DjijQaEc6IkQJDsq3FpKlJ8x0mWtQiuKwUeNQLadYkJmOSZI48rH2dP7JqGmmQuW0QV71DCKPkuQNpV2gkYjsOupbwKexxcqxvhoGUmj1uwAQxvRJBQG3oisxoABKDh6ut+YmM/Ilsz2Umi+GZc+GTeFlTBVJA69ElsVFP/P3fRuuMR/wqKQQ/IJbpiVisCPVpo9/CNRdkx1FCH3N4Q0C1ubIewwuADYa4lOKmzai5cN8BgodhI4qSbrp+xCAfBSVM+Nxcv/SBWXOQojmO4B7jqje3vdcTHis4WDHvV1lJAH9yBtuNCo5K5kCAA0QxI1vgwfbClHLi8t+wBuxRdBAMhU6cl+T1xZu9fO4QZ5cfjjHERDc2bj1IiywrMdWsaro4dTIfCJuEIhKcJytenYqzYvnq+e4RWwK3HdKlFm2UVouskE4ifx8zq8Q9Mnc2A6Wxudcp9qQpGDvyPQKDqP9DJB3tIVmcQmNEP9x8ttilZeBfDxk=
  - secure: Er/1pGI9hcFl6ONl2yraVLW98qPtqChpEaF4vcnp60eM13GrT/MIkgjsY9BEObaOjmJpfWY60vF1G3b1/9Ajss8oe/iPP4k2eNnsOYTR3mU4gV7PGh0C/8VscvzEdoFgFYHfVpCAUtltKCcgXo6z76tKhJsdr/YGdov133i+O5/wu/J3RD6idasqifkpjVSUhZHV/YM+6Qrt9oz5dv5oO16lBh2rS5Fv9PXMhedhC2cuSUC6czJjNMAvN0iNVduC2tLYvJKlpDWxFHmVp0lww796QerZxyf4xCwwxIA8R3V/7I78962f6OVRvbN5IJMbyYXqwOr4ji0deuHfc5jDBdAIgMaD0Gy41NceP6cJdjduSFS3yniLwDCjT5R7eHgb8VoJ/myVkX6LZpUwjGJfJwiOl2DpFM1qIQ6PxZQ5Ni7Xyb/boXsnVc7kJYwEFkiwx6VKDK7JMfcOlD/PlRyXsOYaaELlEuhy1ND3hlp8s9Q/lp5h2eJpcX1GYarEBie2YZKTxhUWYo2NmFNhGymPXMvVDYFivT0n81KV8WvYydFweQV7y4nxK5eUtFRNw4w1Uc6hpz+1eAYcTZqKp4xcYtM/pl753hRScoTHV820YMREMOFwKgiRilCXBdIY8zDchrS+A399vafCjKRgw0ADcLDYwyEap5Plq5Se3KhF0QQ=
