services:
- docker
arch:
- arm64
script:
- docker build -t jchorl/librespot .
deploy:
- provider: script
  script: bash deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD
  on:
    branch: master
env:
  global:
  - secure: LTifDoNLlXWxel2QY7tkJ5j33FiXeW83Vv99bMPGcGs41aJVivcn+XaUR/ayRieau3g/Ed+Hd8MlOm1JrGNGueDIm/q2pv0z/SA+3E/ex2N1Z9ucYwQXFiMtVd3c+rfu4I9bRN8Ep2lOKaNGT1ydXIU1ecrwMRdgpP5C6nuMh1Rk7K4fWFy7U8+wibac/vW21AEiCyZapzyJAk6/9567brgH4Ne88YEDrAyJ/JNHCuoQeg2AlYVkuvzmuaRWVp1xxxndAteVl/MV+3TV1emgXKwb4mA4rf1GCBApg/JyxP9F7mruX6H9onxuVodk9BHFnl/N5UdmbZEXzWIofxK7v8YvPJ2Em6KXMCl/m+tZ3DcWyB3NN1wuFtPlw0YFF43s1XCtIJMe65eNU6nvQE/Pr103K9gsxQrAQbNbCbGhnsqMbXclrl3ZA5h96wmZ7IBk7EB+CZXpXfCRtXNaMOdlnfPA20QSJngCxb6G+5Z+tqef019c41q0kZ4rL/G0j7ySQg8FllM4rzNJaCWe2SY2sV8SBe+1pmqzpEo1vKKrihGH/KS7TIV4u4uyCl+7mU+mhGV8Ah+TCyBi6u6eKYNs+Nyh8WIeemNcyZlLfxT0eLUZFDf7a1x6sicueulAf4LuBsJNdGCjfoG9HC/x4sDCiV0HZBABRcqC6VEG1obFS2Y=
  - secure: OQ/xnJl/PdfpFRLEoTbO9cij5d5Dqa8d0lHqiVlYR3QyHsFNhMvfGwWgsR/aW/7L0xKaSuhJhLj9BX7Er+rhPU8eKt7RsJn4NJQMxrNyruQNNUztZD1b1iEyLvxbuyBEg2wlINYUgzLslzTojWo7tez2y/fKIavUmFu9E2YWIjYn46vJlWSvRtGum5A/7SIOCANfAw+O34KRGy7lVvQsKeAFZHIDfrdFsw9EJB1Aco215jGxbJXqUk4qct2tjsi5QI1mDP/itzvpc1yj/gh1vC7c7YGB6K32CtxPSeDpzqVZOtsXL4jurmBssuDx4kZ3XbY7ADjWzdJ3cN9ZHwTkd6BAS7ervFsI0cZlkfepgb2a39ZWv9wY1DZfvER1hoo6b32m0j3XyIXpAGnLoLXy366Va9nLzH7vrpPfa18M4xu8vJrKjYY18CWkqorbeHcsSB8PY7WBY/aohH8gM1k3OxcqB4Y4XaNPCY7GSmPoykvO4x6Iyk8lzugv6eNoahVtOz7/cskvLu5DfCEc/vXCwczwp4K/dA51t7P+NmnTgvaiFKwslsrOfclwGWhbv6Q47KMrMpCkWp1OnfxECt54YYpYT0ghIRMQJzHtkx9zrqgVEbu5tRXVhdk92KyV/wmRbhN/Z3KerIZRoNzLzSm1Nv6XHTLfd6DRoSoqWX0dxfU=
