services:
- docker
arch:
- arm64
script:
- docker build -t jchorl/librespot .
deploy:
- provider: script
  script: bash deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD
  on:
    branch: master
env:
  global:
  - secure: hhDqYRndxPPnbecgMlAnlT3T41Ew3fobuA9r3u97DUG2idTbSS8jMozznTKuaGhy4l0zvm8RwdkDFtuqufU+R5oUdMiXxyo1JAmACyzBrH+gghDkRNfve45fQcrzqo8T1DLwUr3QXzHwQdxAZegM+Dxwdx+OZ7DqyvETi/UWmrcyPTbPf4rLygA1pHHZ7pNELubXLHAlKX1Qj9UwR7QpOtbNKljCHhlDwHSTEGHzFZEuiP9jsQJiA77Hbik2cNPglw9hGnw7JUBK7578/WvNkEL4aD2qqNy+9sohKDaKShoLglHJzDNpnZv2XtWp7cu0/FiheRRKzwDZZ/lv9yHEl4bb5N3kaqLqW92AB7lAgG3x98duLz1K1v/fR1HGAHMi8izurNzoFhtF9jWQtbi73gkLriY97ItjxFyllmdmgulIRapmO5iL0y2Uz/dplhw5+6IPN5DV4ISNjxJyyNjVpgzVUiR0cklL5P0An82yvZTguuUZ4mUUu4lOvmZAwMnrz1FpWLWU0o3daIgWtqkI26yqEKkeWvwdmj4bI9x2AwLGjAi86mypcblIT/FfZoqgQYiuvMinUy2/vy9zNtlDDeTL9/IuhwZqP0jCIhK187xC0NqmX+BO0gsvqMgQrVP7ul67m3EUitlwXgsq46lgZSAn2ph5wZntS8vtIAUuB8w=
  - secure: L+Z+RLXRK0RMQh8Q2H2MjMHOgWfi9X7gIOO1JoKb9L8j5jz3FTLwUx+Kc9ZQ29NOpH18ttKl0tHV3Mq4QvPiNsaMhMFx8QRVJ8fznIydm4NKWulru6oOPNzLQUycaeagYaHNQXPC0t4GzzHFNGqfG9KD8ah1F8xjKj/72ZQQVjPcYC7p/cxXprCmbbMlF8nUacsADrQi0D2piZRake6Xa7sZ7fN290D++CgosEPmy85nSNSnNoXLefdL5Sz36YxZGoKPtLO08FthvrthLczVLXG/b00bhWq87aBoF2wJ3LUdHCUjf8C1F4xzYkuztWC1ytEY5jqnzmb4EHBS74u1nXsJ8iSnbMZzrWyo/fW6XJxCepFvFBRn6VaGYN3A7vtxiJyMYdpUK7xUsRJehuwkbYCvV9bgKxVL24ZCDGVfHSodT9ZTMu7khWt4jZPxI4fbWVY61YRr0mu2jOYzeDtSZdjsuRGBCCQc01b6auJgoQvBob2elJQd7Ka2czHIsapUYSvOnXxp63VSsbX9B9ZKYh1zowNsXSNsLyeXNKHAP09PJpT10vMs53q5bDhcupsmRZrEZyDn584wWfUlitnlcXb9LjVG2Z4TxuWARhMSKppC9aUiUTPt4uIBdoW5WPpn164CKJ7OI5TeEFhqix/dErG6VZvx4ZuFCt9+7QVRNcU=
